// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package invite

import (
	"database/sql"
	"time"
)

type Invite struct {
	ID          int64        `json:"id"`
	UserID      int64        `json:"userId"`
	InviteHash  string       `json:"inviteHash"`
	IsActivated bool         `json:"isActivated"`
	CreatedAt   time.Time    `json:"createdAt"`
	UpdatedAt   time.Time    `json:"updatedAt"`
	DeletedAt   sql.NullTime `json:"deletedAt"`
}
