// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package post

import (
	"database/sql"
	"time"
)

type Post struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"userId"`
	Title       string         `json:"title"`
	Short       string         `json:"short"`
	Body        string         `json:"body"`
	Tags        sql.NullString `json:"tags"`
	IsPublished bool           `json:"isPublished"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
	DeletedAt   sql.NullTime   `json:"deletedAt"`
}
