// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package invite

import (
	"context"
)

type Querier interface {
	Activate(ctx context.Context, id int64) (*Invite, error)
	CreateOrUpdate(ctx context.Context, arg CreateOrUpdateParams) (*Invite, error)
	Delete(ctx context.Context, id int64) error
	GetActiveByUserID(ctx context.Context, id int64) (*Invite, error)
	GetAllByUserID(ctx context.Context, userID int64) ([]*Invite, error)
	GetByID(ctx context.Context, id int64) (*Invite, error)
	GetByInviteHash(ctx context.Context, inviteHash string) (*Invite, error)
}

var _ Querier = (*Queries)(nil)
