// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package session

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createOrUpdateStmt, err = db.PrepareContext(ctx, createOrUpdate); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOrUpdate: %w", err)
	}
	if q.deleteBySessionHashStmt, err = db.PrepareContext(ctx, deleteBySessionHash); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBySessionHash: %w", err)
	}
	if q.getBySessionHashStmt, err = db.PrepareContext(ctx, getBySessionHash); err != nil {
		return nil, fmt.Errorf("error preparing query GetBySessionHash: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createOrUpdateStmt != nil {
		if cerr := q.createOrUpdateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOrUpdateStmt: %w", cerr)
		}
	}
	if q.deleteBySessionHashStmt != nil {
		if cerr := q.deleteBySessionHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBySessionHashStmt: %w", cerr)
		}
	}
	if q.getBySessionHashStmt != nil {
		if cerr := q.getBySessionHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBySessionHashStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                      DBTX
	tx                      *sql.Tx
	createOrUpdateStmt      *sql.Stmt
	deleteBySessionHashStmt *sql.Stmt
	getBySessionHashStmt    *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                      tx,
		tx:                      tx,
		createOrUpdateStmt:      q.createOrUpdateStmt,
		deleteBySessionHashStmt: q.deleteBySessionHashStmt,
		getBySessionHashStmt:    q.getBySessionHashStmt,
	}
}
