// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package session

import (
	"database/sql"
	"time"
)

type Session struct {
	ID          int64        `json:"id"`
	UserID      int64        `json:"userId"`
	SessionHash string       `json:"sessionHash"`
	CreatedAt   time.Time    `json:"createdAt"`
	UpdatedAt   time.Time    `json:"updatedAt"`
	DeletedAt   sql.NullTime `json:"deletedAt"`
}
