// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package session

import (
	"context"
)

type Querier interface {
	CreateOrUpdate(ctx context.Context, arg CreateOrUpdateParams) (*Session, error)
	DeleteByID(ctx context.Context, id int64) error
	GetByUserID(ctx context.Context, sessionHash string) (*Session, error)
}

var _ Querier = (*Queries)(nil)
