// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: session.sql

package session

import (
	"context"
)

const createOrUpdate = `-- name: CreateOrUpdate :one
INSERT INTO sessions (user_id, session_hash)
VALUES (?, ?)
ON CONFLICT (user_id) DO UPDATE
SET session_hash = excluded.session_hash, updated_at = datetime('now'), deleted_at = NULL
RETURNING id, user_id, session_hash, created_at, updated_at, deleted_at
`

type CreateOrUpdateParams struct {
	UserID      int64  `json:"userId"`
	SessionHash string `json:"sessionHash"`
}

// CreateOrUpdate
//
//	INSERT INTO sessions (user_id, session_hash)
//	VALUES (?, ?)
//	ON CONFLICT (user_id) DO UPDATE
//	SET session_hash = excluded.session_hash, updated_at = datetime('now'), deleted_at = NULL
//	RETURNING id, user_id, session_hash, created_at, updated_at, deleted_at
func (q *Queries) CreateOrUpdate(ctx context.Context, arg CreateOrUpdateParams) (*Session, error) {
	row := q.queryRow(ctx, q.createOrUpdateStmt, createOrUpdate, arg.UserID, arg.SessionHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const deleteBySessionHash = `-- name: DeleteBySessionHash :exec
UPDATE sessions
SET deleted_at = datetime('now')
WHERE session_hash = ?
  AND deleted_at IS NULL
`

// DeleteBySessionHash
//
//	UPDATE sessions
//	SET deleted_at = datetime('now')
//	WHERE session_hash = ?
//	  AND deleted_at IS NULL
func (q *Queries) DeleteBySessionHash(ctx context.Context, sessionHash string) error {
	_, err := q.exec(ctx, q.deleteBySessionHashStmt, deleteBySessionHash, sessionHash)
	return err
}

const getBySessionHash = `-- name: GetBySessionHash :one
SELECT id, user_id, session_hash, created_at, updated_at, deleted_at
FROM sessions
WHERE session_hash = ?
  AND deleted_at IS NULL
`

// GetBySessionHash
//
//	SELECT id, user_id, session_hash, created_at, updated_at, deleted_at
//	FROM sessions
//	WHERE session_hash = ?
//	  AND deleted_at IS NULL
func (q *Queries) GetBySessionHash(ctx context.Context, sessionHash string) (*Session, error) {
	row := q.queryRow(ctx, q.getBySessionHashStmt, getBySessionHash, sessionHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}
