// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package password

import (
	"database/sql"
	"time"
)

type Password struct {
	ID             int64        `json:"id"`
	UserID         int64        `json:"userId"`
	PasswordHash   string       `json:"passwordHash"`
	FailedAttempts int64        `json:"failedAttempts"`
	CreatedAt      time.Time    `json:"createdAt"`
	UpdatedAt      time.Time    `json:"updatedAt"`
	DeletedAt      sql.NullTime `json:"deletedAt"`
	BlockedAt      sql.NullTime `json:"blockedAt"`
}
