// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package password

import (
	"context"
)

type Querier interface {
	Create(ctx context.Context, arg CreateParams) (*Password, error)
	GetByUserID(ctx context.Context, userID int64) (*Password, error)
	IncreaseFailedAttempts(ctx context.Context, id int64) (*Password, error)
	ResetFailedAttempts(ctx context.Context, id int64) (*Password, error)
	Update(ctx context.Context, arg UpdateParams) (*Password, error)
}

var _ Querier = (*Queries)(nil)
