// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package user

import (
	"database/sql"
	"time"
)

type User struct {
	ID            int64          `json:"id"`
	Username      string         `json:"username"`
	DisplayedName string         `json:"displayedName"`
	Email         sql.NullString `json:"email"`
	InvitedByUser int64          `json:"invitedByUser"`
	CreatedAt     time.Time      `json:"createdAt"`
	UpdatedAt     time.Time      `json:"updatedAt"`
	DeletedAt     sql.NullTime   `json:"deletedAt"`
}
